// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUAuRP8OryolLhDJhUvepf1zJ22kG_quo',
    appId: '1:464086873108:web:2645456b350ee159986301',
    messagingSenderId: '464086873108',
    projectId: 'enrollment-flutter',
    authDomain: 'enrollment-flutter.firebaseapp.com',
    storageBucket: 'enrollment-flutter.appspot.com',
    measurementId: 'G-H2S32Q535W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4PwsFXNybT8wiG_l2yGfl92qpNdzN1XE',
    appId: '1:464086873108:android:cfc43a1fe2ab1240986301',
    messagingSenderId: '464086873108',
    projectId: 'enrollment-flutter',
    storageBucket: 'enrollment-flutter.appspot.com',
  );
}
