// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAarZnBAEBH0ab5Cd6bt1ICcDjUKfWdym0',
    appId: '1:124724628822:web:b3d1cab16d3e3eac021af7',
    messagingSenderId: '124724628822',
    projectId: 'se102-64409',
    authDomain: 'se102-64409.firebaseapp.com',
    databaseURL: 'https://se102-64409-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'se102-64409.appspot.com',
    measurementId: 'G-9NWKB30GC8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhsm2HL6bybDKF7nQul5TpRKh9wMUlN0Q',
    appId: '1:124724628822:android:dcd8f33dde57c997021af7',
    messagingSenderId: '124724628822',
    projectId: 'se102-64409',
    databaseURL: 'https://se102-64409-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'se102-64409.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5Evga0m754hS7tGeRpwi3DruRrS0e2Pg',
    appId: '1:124724628822:ios:07c520651de434ec021af7',
    messagingSenderId: '124724628822',
    projectId: 'se102-64409',
    databaseURL: 'https://se102-64409-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'se102-64409.appspot.com',
    iosClientId: '124724628822-iqvcakgi7n5cc8n0qu25svqcth7s51op.apps.googleusercontent.com',
    iosBundleId: 'com.example.hnuMisAnnouncement',
  );
}
